import type { QuestionRecord } from '../types/question'

export const questionCatalog: QuestionRecord[] = [
  {
    id: 101,
    title: '基层治理中的“最后一公里”协同',
    category: '真题',
    source: '2024 国考副省',
    year: 2024,
    region: '全国',
    questionType: '概括题',
    difficulty: '进阶',
    theme: '基层治理',
    materialCount: 3,
    suggestedMinutes: 45,
    aiSupported: true,
    tags: ['治理协同', '群众服务', '概括归纳'],
    coverNote: '练概括问题和提炼措施。',
    intro: '聚焦基层协同堵点，练抽取问题和归纳举措。',
    overview: '适合练问题抽象和概括作答。',
    tasks: ['概括协同治理中的主要堵点', '提炼基层服务流程优化方向'],
    instructions: ['先按材料主体分类，再按问题-原因-建议整理框架。', '注意概括语言和案例语言的区分。'],
    notices: ['答题时建议先列清单再组织表述。', 'AI 结果仅作训练参考。'],
    materials: [
      {
        id: 'm1',
        title: '材料一：社区网格协同',
        summary: '多个治理主体各自为战，居民诉求在不同系统间重复流转。',
        content: '某社区建立了网格化管理机制，但居民反映诉求时仍需重复填写信息，不同部门之间共享效率不高，问题处理链路长、反馈慢。',
      },
      {
        id: 'm2',
        title: '材料二：热线与属地联动',
        summary: '热线平台和属地处置之间存在信息断层。',
        content: '热线平台能够快速收集问题，但在派单后缺少统一跟踪面板，基层处置单位难以及时回写结果，群众难以感知办理进度。',
      },
      {
        id: 'm3',
        title: '材料三：数字治理实践',
        summary: '通过“一张表单、一次采集”缩短办理链路。',
        content: '某地通过统一表单、统一账号和部门协同看板，实现一次采集多方共享，群众平均办理时长显著下降。',
      },
    ],
    answerSections: [
      {
        id: 'a1',
        title: '问题概括',
        prompt: '请概括基层治理协同中的主要堵点。',
        wordLimitLabel: '建议 250-350 字',
        minWords: 220,
        placeholder: '先概括问题类型，再归纳具体表现。',
      },
      {
        id: 'a2',
        title: '优化方向',
        prompt: '结合材料提出改进协同治理的方向。',
        wordLimitLabel: '建议 250-350 字',
        minWords: 220,
        placeholder: '围绕流程、平台、机制三个维度组织答案。',
      },
    ],
    referenceAnswer: '基层治理“最后一公里”协同堵点主要体现在信息重复采集、平台之间互不联通、办理过程缺乏闭环追踪以及部门职责边界不清等方面。优化方向上，应推进统一入口、统一台账、统一反馈机制，形成数据共享、流程协同和结果回看的一体化治理链路。',
    optimizedExample: '可从“入口统一、过程协同、结果闭环”三个层次作答，先写问题再对应措施，使概括更稳、层次更清楚。',
  },
  {
    id: 102,
    title: '夜间经济如何兼顾活力与秩序',
    category: '模拟题',
    source: '平台模拟卷 A',
    year: 2025,
    region: '华东',
    questionType: '对策题',
    difficulty: '进阶',
    theme: '城市发展',
    materialCount: 2,
    suggestedMinutes: 40,
    aiSupported: true,
    tags: ['夜间经济', '城市治理', '对策题'],
    coverNote: '练从矛盾里提出平衡型对策。',
    intro: '围绕夜市、商圈和居民投诉，提出兼顾活力与秩序的方案。',
    overview: '适合练对策拆解和措施排序。',
    tasks: ['分析夜间经济发展的主要矛盾', '提出兼顾活力与秩序的治理对策'],
    instructions: ['对策题要区分原则性表述和执行层措施。', '可以按“规划-治理-服务”拆分答案。'],
    notices: ['注意体现精细化治理，不宜只写“加强监管”。'],
    materials: [
      {
        id: 'm1',
        title: '材料一：夜市扩张',
        summary: '夜市提升消费活力，但也带来噪音、卫生和交通压力。',
        content: '多个商圈在延长营业时间后带动了客流增长，但居民投诉噪音、占道经营和停车难的问题同步上升。',
      },
      {
        id: 'm2',
        title: '材料二：分区治理试点',
        summary: '通过分时分区经营、统一保洁和巡查机制提升治理效果。',
        content: '试点区域将商户纳入分区经营清单，设置夜间保洁与柔性执法机制，并通过数据看板监测投诉和客流，实现“热度”与“秩序”兼顾。',
      },
    ],
    answerSections: [
      {
        id: 'a1',
        title: '主要矛盾',
        prompt: '请概括夜间经济发展中的主要矛盾。',
        wordLimitLabel: '建议 180-260 字',
        minWords: 160,
        placeholder: '围绕活力、秩序、居民感受三个维度写。',
      },
      {
        id: 'a2',
        title: '治理对策',
        prompt: '请提出兼顾活力与秩序的治理对策。',
        wordLimitLabel: '建议 280-380 字',
        minWords: 250,
        placeholder: '可从规划、服务、协同治理三方面作答。',
      },
    ],
    referenceAnswer: '夜间经济发展的核心矛盾在于消费活力提升与城市秩序承载之间的张力。要坚持分区分类管理，完善商圈配套、建立联动巡查与投诉闭环机制，并以精细化服务提升商户和居民的双向获得感。',
    optimizedExample: '答题时可先写“矛盾体现”，再写“分区规划、配套保障、协同治理、数据监测”四条对策，避免泛泛而谈。',
  },
  {
    id: 103,
    title: '青年返乡与县域新机会',
    category: '专项训练',
    source: '写作专项练习',
    year: 2025,
    region: '全国',
    questionType: '大作文',
    difficulty: '冲刺',
    theme: '青年发展',
    materialCount: 4,
    suggestedMinutes: 70,
    aiSupported: true,
    tags: ['青年返乡', '县域经济', '大作文'],
    coverNote: '练大作文立意和论证结构。',
    intro: '围绕返乡创业、公共服务和平台连接组织论述。',
    overview: '适合练立意、分论点和材料选择。',
    tasks: ['提炼核心论点', '围绕县域机会组织三段式论证'],
    instructions: ['先定立意，再按“机会来源-发展条件-制度保障”搭结构。', '注意论据不要与标题脱节。'],
    notices: ['大作文更考验结构和过渡句，建议先写提纲。'],
    materials: [
      {
        id: 'm1',
        title: '材料一：返乡创业样本',
        summary: '返乡青年把新业态与本地产业结合，形成新的就业吸附能力。',
        content: '多地青年返乡后依托电商、文旅和农产品品牌化，带动本地供应链升级，也重塑了乡村的社会分工。',
      },
      {
        id: 'm2',
        title: '材料二：公共服务改善',
        summary: '教育、医疗、交通等公共服务改善，增强了青年长期留下来的意愿。',
        content: '县域综合服务能力的提升，让青年返乡不再意味着放弃生活品质，而是重新选择更适合自己的发展路径。',
      },
      {
        id: 'm3',
        title: '材料三：平台连接',
        summary: '数字平台降低了返乡创业的市场连接门槛。',
        content: '直播、电商、供应链平台让县域产品和服务更容易触达外部市场，使返乡青年拥有更丰富的成长通道。',
      },
      {
        id: 'm4',
        title: '材料四：制度支持',
        summary: '政策支持决定返乡从个体选择变成持续趋势。',
        content: '只有在金融、培训、场地、治理等制度支持同步到位时，青年返乡的个案才能转化为县域发展的可持续势能。',
      },
    ],
    answerSections: [
      {
        id: 'a1',
        title: '作文提纲',
        prompt: '请先列出文章提纲。',
        wordLimitLabel: '建议 180-260 字',
        minWords: 150,
        placeholder: '先写标题、总论点，再写 3 个分论点。',
      },
      {
        id: 'a2',
        title: '正式成文',
        prompt: '请完成一篇议论文。',
        wordLimitLabel: '建议 800-1000 字',
        minWords: 700,
        placeholder: '围绕“机会、条件、保障”展开完整论证。',
      },
    ],
    referenceAnswer: '青年返乡不是简单的空间回流，而是在县域新机遇和制度支持共同作用下，对个人发展与地方振兴关系的一次重新定义。县域只有把产业机会、公共服务和制度保障统筹起来，才能让返乡成为更多青年可持续的选择。',
    optimizedExample: '大作文可从“看见机会、留住人才、形成生态”三个分论点展开，结尾再回扣县域发展与青年成长的双向成就。',
  },
]

export const questionCategories = ['全部', '真题', '模拟题', '专项训练'] as const

export function getQuestionById(questionId: number) {
  return questionCatalog.find((item) => item.id === questionId) ?? null
}
